name: serenmind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  logger: ^2.4.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.7
  firebase_storage: ^12.3.3
  shared_preferences: ^2.3.2
  carousel_slider: ^5.0.0
  audioplayers: ^6.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/music/
    - assets/images/menu/
    - assets/images/mood/
    - assets/images/splash/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo/white_splash.png
  color_dark: "#121212"
  image_dark: assets/images/logo/black_splash.png

  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/logo/white_splash.png
    icon_background_color_dark: "#121212"
    image_dark: assets/images/logo/black_splash.png

  web: false

