name: serenmind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  logger: ^2.4.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700

flutter_native_splash:
  background_image: "assets/images/logo_v2.png"
  color: "#ffffff"
  image: assets/images/logo_v2.png
  branding: assets/images/logo_v2.png
  color_dark: "#121212"
  image_dark: assets/images/logo_v2.png
  branding_dark: assets/images/logo_v2.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"
  fullscreen: true
  web: false

